### ISSUE TITLE
LVGL as ESP-IDF component

### ISSUE THREAD

**Issue by C47D** [lvgl/lvgl#1869]
We've been using LVGL as an ESP-IDF component on the lv_port_esp32 repo, that's accomplished by adding some "especial" files to it so it. This issue is to keep track of the changes done to LVGL so it can be used directly as a component. The Kconfig file also should work for other projects like Zephyr and Nuttx, so any feedback is welcome.

- [x] Create an Kconfig file with all (or most) of the LVGL configuration options. See #1875 
- [x] lv_conf_kconfig: Update as necessary. See #1870
- [x] lv_conf_internal: Include special ESP-IDF header files when working with the ESP-IDF framework. See #1864 
- [x] lv_conf_internal: Update as necessary.
- [x] Create an CMakeLists.txt file for (ESP-IDF) component registration. See #1868

**Comment by C47D** [comment]
@kisvegabor @embeddedt Some LVGL configuration options depends on another options being enabled, e.g. `LV_SPINNER_DEF_ARC_LENGTH` depends on `LV_USE_SPINNER` being enabled. Should we hide `LV_SPINNER_DEF_ARC_LENGTH` in the menuconfig interface when `LV_USE_SPINNER` is not enabled? (same for all other options)

**Comment by embeddedt** [comment]
Yes; I think that would make the most sense. Otherwise the Kconfig interface will be cluttered with options which don't change anything.

**Comment by C47D** [comment]
Nice, I will send a draft PR later today with the Kconfig file.

**Comment by kisvegabor** [comment]
I agree, it'd be better to hide them.

**Comment by C47D** [comment]
@kisvegabor in `lv_conf_internal.h` I manually added `lv_color_hex` when using the `CONFIG_LV_COLOR_TRANSP` value, is this correct? If so, how can we add `lv_color_hex` when using the `lv_conf_checker.py` script?

```c
/*Images pixels with this color will not be drawn (with chroma keying)*/
#ifndef LV_COLOR_TRANSP
#  ifdef CONFIG_LV_COLOR_TRANSP
#    define LV_COLOR_TRANSP lv_color_hex(CONFIG_LV_COLOR_TRANSP)
#  else
#    define  LV_COLOR_TRANSP    LV_COLOR_LIME         /*LV_COLOR_LIME: pure green*/
#  endif
#endif
```

Also to let you know that I've tested the new Kconfig with the latest `dev` and it seems to be working as expected.

**Comment by kisvegabor** [comment]
Can we handle `LV_COLOR_TRANSP` similarly to theme colors in `lv_conf_kconfig.h`?

**Comment by C47D** [comment]
@kisvegabor I've pushed c2094b9 to handle `LV_COLOR_TRANSP`, it defines `CONFIG_LV_COLOR_TRANSP`, so `lv_conf_internal.h` doesn't need to change to handle that option.

**Comment by kisvegabor** [comment]
Thanks!

**Comment by C47D** [comment]
Hi @kisvegabor @embeddedt 
Should we keep this issue open for feedback or can we close it?

**Comment by kisvegabor** [comment]
I suggest closing this and let people opening issues for specific issues.

I think one more step remained. We need to let people know how LVGL can be used as an ESP component. Similar to the [Arduino docs here](https://docs.lvgl.io/latest/en/html/get-started/arduino.html).

Carlos, do you still have time and energy to write a few lines about it?

**Comment by C47D** [comment]
I can do something about it at night.

**Comment by kisvegabor** [comment]
As all tasks are done here so let's close this issue. 

Thank you @C47D for the great work! :clap: :clap: :clap:
